"""Add columns

Revision ID: 66ab7230cf0b
Revises: 4e2d120de87f
Create Date: 2025-02-26 11:51:24.268803

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66ab7230cf0b'
down_revision = '4e2d120de87f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('category', sa.String(length=100), nullable=False))
    op.add_column('event', sa.Column('featured', sa.Boolean(), nullable=True))
    op.add_column('event', sa.Column('image', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'image')
    op.drop_column('event', 'featured')
    op.drop_column('event', 'category')
    # ### end Alembic commands ###
